# Generated by Django 4.2.9 on 2024-02-10 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tool", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CSVFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("csv_file", models.FileField(upload_to="static/output/")),
            ],
        ),
        migrations.CreateModel(
            name="ImgFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image_file", models.FileField(upload_to="static/output/")),
            ],
        ),
        migrations.RemoveField(
            model_name="processedfiles",
            name="csv_file",
        ),
        migrations.RemoveField(
            model_name="processedfiles",
            name="image_file",
        ),
        migrations.AddField(
            model_name="processedfiles",
            name="csv_files",
            field=models.ManyToManyField(to="tool.csvfile"),
        ),
        migrations.AddField(
            model_name="processedfiles",
            name="image_files",
            field=models.ManyToManyField(to="tool.imgfile"),
        ),
    ]
