# Generated by Django 4.2.9 on 2024-02-16 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tool", "0002_csvfile_imgfile_remove_processedfiles_csv_file_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="uploadedfile",
            name="zip_file",
            field=models.FileField(
                blank=True, default=None, null=True, upload_to="static/zip/"
            ),
        ),
    ]
